### ISSUE TITLE
Regression weights not found

### ISSUE THREAD

**Issue by luhong88** [seanrjohnson/protein_gibbs_sampler#14]
While calling the `likelihood_esm.py` script to score sequences with ESM-1v, I received the following error 
```
python-3.7.8/lib/python3.7/site-packages/esm/pretrained.py:216: UserWarning: Regression weights not found, predicting contacts will not produce correct results.
```
My understanding is that this will not affect the calculations performed by the script, but I just want to double check here to be sure. Thanks!

**Comment by seanrjohnson** [comment]
Yeah we're not predicting contact maps,so it doesn't affect the scores.
