### ISSUE TITLE
Setting up Container Env: Missing docker image and directories

### ISSUE THREAD

**Issue by KahiniWadhawan** [seanrjohnson/protein_gibbs_sampler#2]
There are a lot of paths that are hardcoded in makefile and other parts of the code that are running into issues. 
When running `make run-cpu`
Missing docker image as required in Makefile in following line
`DOCKER_IMAGE=massiekm/dl-pgen:latest`

Please, provide detailed setup instructions and docker image as well.

**Comment by seanrjohnson** [comment]
You're absolutely right. The install instructions are not as easy as they should be. It is definitely something I will continue to work on.
However, that docker image does exist:
https://hub.docker.com/r/massiekm/dl-pgen

You might also look at the branch "esm1b_followup", which is our current working branch.
https://github.com/seanrjohnson/protein_gibbs_sampler/tree/esm1b_followup

In particular there is a file there called [datacrunch_setup.sh](https://github.com/seanrjohnson/protein_gibbs_sampler/blob/esm1b_followup/datacrunch_setup.sh)
which is the script I use to deploy the library on cloud nodes at datacrunch.io, so it should help you figure out how to deploy it from scratch.

Even with that though, I agree that more should be done to make it easier to install and run. And we still have a lot of work to do with the documentation.

**Comment by seanrjohnson** [comment]
We added some more documentation and install instructions, as well as command-line utilities so new sequences can be generated without needing to write any new python code.

Still have not had a chance to simplify the docker image, but hopefully these changes are a step in the right direction.

**Comment by seanrjohnson** [comment]
Still no docker image, but the conda install seems to be fairly robust, so closing this issue.
